apiVersion: apps/v1 
kind: Deployment
metadata:
  name: tetrisbac-deployment
  labels:
    app: tetrisbac
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tetrisbac
  template:
    metadata:
      labels:
        app: tetrisbac
    spec:
      containers:
      - name: tetrisbac
        image: jatinthakur029/tetris-backend:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secret
