name: Deploy Infrastructure

on:
    push:
        branches: 
            - main
        paths:
            - 'terraform/**'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-1  

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              
            - name: Terraform init
              working-directory: terraform
              run: terraform init

            - name: Terraform Validate
              working-directory: terraform
              run: terraform validate

<<<<<<< HEAD
=======
            
>>>>>>> 85894983023c8a75da07c9d3ba795f5720f278da
              
            - name: Terraform Plan
              working-directory: terraform
              run: terraform plan
              
            - name: Terraform Apply
              working-directory: terraform
              run: terraform apply -auto-approve  

        
